version: '3.2'
services:
  app:
    image: contactos:2
    container_name: contactos_app
    expose:
      - 8888
    networks:
      - contactos_net
    depends_on:
      - proxy
  proxy:
    image: nginx:1.27.3
    container_name: contactos_proxy
    labels:
      - traefik.enable=true
#      - traefik.docker.network=web
#      - traefik.http.middlewares.jellyfin.redirectscheme.scheme=https
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.routers.jellyfin.rule=Host(`agenda.localhost`)
#      - traefik.http.routers.jellyfin.tls=true
#      - traefik.http.routers.jellyfin.https.entrypoints.=websecure
    networks:
      - contactos_net
    ports:
      - 8081:80
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/contactos.conf:/etc/nginx/conf.d/default.conf

networks:
  contactos_net:
    name: red_contactos
    driver: bridge

#volumes:
#  nginx-vol:
#    t
